select
    CODIGOINVENTARIO,
    SEQUENCIAETIQUETA,
    CODIGOPRODUTO,
    TIPOUA,
    ENDERECO,
    ETIQUETAENDERECO,
    CODIGOUA,
    ETIQUETAUA,
    LOTEFABRICACAO,
    LOTEGERAL,
    DATAFABRICACAO,
    DATAVENCIMENTO,
    QUANTIDADEINVENTARIO,
    QUANTIDADEESTOQUE,
    DATAINICIO,
    DATAFIM
from ORAINT.INVENTARIO
fetch first 500 rows only
