select
    SEQUENCIAMOVIMENTOESTOQUE,
    NUMEROMOVIMENTO,
    CODIGODEPOSITANTE,
    CODIGOEMPRESA,
    CODIGOPRODUTO,
    TIPODOCUMENTO,
    SERIEDOCUMENTO,
    NUMERODOCUMENTO,
    TIPOUC,
    QUANTIDADEMOVIMENTO,
    LOTEFABRICACAOORIGEM,
    LOTEFABRICACAODESTINO,
    DATAVENCIMENTOORIGEM,
    DATAVENCIMENTODESTINO
from ORAINT.MOVIMENTOESTOQUE
fetch first 500 rows only
