select
    SEQUENCIADOCUMENTO,
    NUMERODOCUMENTO,
    SERIEDOCUMENTO,
    TIPODOCUMENTO,
    CODIGODEPOSITANTE,
    CODIGOEMPRESA,
    CODIGOENTREGA,
    ROTA,
    SUBROTA,
    SEQUENCIAPEDIDO,
    DATAEMISSAO,
    DATAPREVISAOMOVIMENTO,
    DATAENTREGA,
    DATAMOVIMENTO,
    DATAAGENDAMENTO,
    VALORTOTALDOCUMENTO,
    VALORTOTALPRODUTO,
    VALORFRETE,
    VALORDESCONTO
from ORAINT.DOCUMENTO
fetch first 500 rows only
