dbt_wms:
  target: local
  outputs:
    local:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'wmsadmin') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'wmsadmin2026') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'wms') }}"
      schema: gold
      threads: 4
