apiVersion: 1

datasources:
  - name: Airflow PostgreSQL
    type: postgres
    url: wms-postgres:5432
    user: wmsadmin
    secureJsonData:
      password: "wmsadmin2026"
    jsonData:
      database: airflow
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: false
    editable: true
