name: dbt Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Implement dbt run/test pipeline"
