name: Build and Push Lambda Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - requirements.txt
      - app/**
      - pipelines/**
      - .github/workflows/deploy-lambda-image.yml

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "896159010925"
  ECR_REPOSITORY: wms-data-platform-dev-lambda
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG \
            .

      - name: Push image
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
