name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    branches: [dev, main]
    paths:
      - "app/**"
      - "pipelines/**"
      - "Dockerfile"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t wms-lambda .
