name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "transform/dbt_wms/**"
      - "app/api/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Implement dbt docs and OpenAPI publish"
